[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "#414868"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"

[colors.normal]
black = "#15161E"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#a9b1d6"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[font]
size = 14
normal.family = "JetBrainsMono NF"
normal.style = "Regular"
bold.family = "JetBrainsMono NF"
bold.style = "Bold"
bold_italic.family = "JetBrainsMono NF"
bold_italic.style = "Italic"
italic.family = "JetBrainsMono NF"
italic.style = "Italic"

[terminal.shell]
program = "/bin/tmux"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.4

[terminal]
